### PR TITLE
I/166 region mouse select

### PR DESCRIPTION
**Pull request by weiren2**
@jbpagliuco you can confirm the pull request when you are done with region names.

### CODE REVIEW

**Comment by jonthaler** [comment]
Should this work now:

average_pixel ffbox ffview amp01data

It fails for me.

Also, on my Mac ctl-click brings up a contextual menu.  Can we change the trigger to Opt-click (or, maybe just a simple click)?

Jon

**Comment by weiren2** [comment]
It should work now. I just updated the code on the server. It will show the region as a yellow box if you type average_pixel ffbox ffview amp01data.


Wei

________________________________

**Comment by jonthaler** [comment]
Yes, it works for me now.  I am not able to test Joe’s region capture method, due to the behavior of ctl-click on the Mac.

The yellow boundary is hard to see.  We’ll have to think more about colors.

Good work,
Jon

**Comment by weiren2** [comment]
Right. But white boundary is even harder to see (at least for me).


Wei

________________________________

**Pull request merged**
